// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNALiCKlvlhhrM2jDyiKNRuVsy61DYmbc',
    appId: '1:838294265017:web:64f807e1a6357002decf68',
    messagingSenderId: '838294265017',
    projectId: 'askio-de495',
    authDomain: 'askio-de495.firebaseapp.com',
    storageBucket: 'askio-de495.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6bNkKo9XoG57H3F8CNjoRjSyypjBGyY',
    appId: '1:838294265017:android:bbf6f09ce0a7464adecf68',
    messagingSenderId: '838294265017',
    projectId: 'askio-de495',
    storageBucket: 'askio-de495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpfTDMt4BruZG2f46Y8uavOdvgjxDmRc',
    appId: '1:838294265017:ios:04a54f0c1df2c725decf68',
    messagingSenderId: '838294265017',
    projectId: 'askio-de495',
    storageBucket: 'askio-de495.firebasestorage.app',
    iosBundleId: 'com.example.askio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpfTDMt4BruZG2f46Y8uavOdvgjxDmRc',
    appId: '1:838294265017:ios:04a54f0c1df2c725decf68',
    messagingSenderId: '838294265017',
    projectId: 'askio-de495',
    storageBucket: 'askio-de495.firebasestorage.app',
    iosBundleId: 'com.example.askio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNALiCKlvlhhrM2jDyiKNRuVsy61DYmbc',
    appId: '1:838294265017:web:80b1f8edffe17d70decf68',
    messagingSenderId: '838294265017',
    projectId: 'askio-de495',
    authDomain: 'askio-de495.firebaseapp.com',
    storageBucket: 'askio-de495.firebasestorage.app',
  );
}
